# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
    - 2.11.5
jdk:
    - oraclejdk7
    - openjdk7
script: "sbt ++$TRAVIS_SCALA_VERSION clean coverage test"
after_success: "sbt coveralls"
